---
- name: Ensure required packages are installed
  ansible.builtin.package:
    name: "{{ pxe_packages }}"
    state: present

- name: Ensure firewalld is enabled and running
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Ensure nginx is enabled and running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Ensure dnsmasq is enabled and running
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true

- name: Ensure TFTP socket is enabled and running
  ansible.builtin.systemd:
    name: tftp.socket
    state: started
    enabled: true

